server:
  port: 8082  #订单微服务的端口号

goods:
  item:
    url: http://127.0.0.1:8081/goods/

spring:
  application:
    name: microservice-orders #指定服务名

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/,http://admin:admin@127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    #ip-address: 127.0.0.1 #指定ip
    instance-id: ${spring.application.name}:${server.port} #指定实例

#设置负载均衡的为随机
microservice-goods:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule